version: '3.12'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env

  db:
    image: postgres:latest
    env_file:
      - .env